using RogueDeck.Core.Combat;
using static BnbContent.Converter.Cards.CardAuthoring;

namespace BnbContent.Converter.Cards;

// The Bureaucrat's opening hand and the four kinds of rubbish the deck learns to generate.
//
// Starting resources: 70 HP, 3 Energy. The starter cards are not part of the 80-card reward pool and are
// never offered as rewards; the Junk cards are generated by other cards and are never offered either.
public static class BureaucratStarter
{
    // ── the starting deck ─────────────────────────────────────────────────────────────────────────────────

    public static readonly BnbCard PaperCut = new(
        "paper_cut", "Paper Cut", DeedTag, 1,
        "Deal 6 damage.",
        Damage(6),
        Rarity: "starter");

    public static readonly BnbCard CowerBehindADesk = new(
        "cower_behind_a_desk", "Cower Behind a Desk", WorkingTag, 1,
        "Gain 5 Block.",
        Block(5),
        Rarity: "starter");

    public static readonly BnbCard StrongBinder = new(
        "strong_binder", "Strong Binder", WorkingTag, 1,
        "Gain 7 Block. Apply 1 Doubt.",
        Seq(Block(7), Apply(Keywords.Doubt, 1)),
        Rarity: "starter", Tags: [ArgumentTag]);

    public static readonly BnbCard PermitA38 = new(
        "permit_a38", "Permit A38", WorkingTag, 2,
        "Apply 5 Paperwork.",
        Apply(Keywords.Paperwork, 5),
        Rarity: "starter", Tags: [FormTag, PermitTag]);

    // Four Paper Cuts, four Cowers, one Binder, one Permit.
    public static IReadOnlyList<string> Deck() =>
    [
        .. Enumerable.Repeat(PaperCut.Id, 4),
        .. Enumerable.Repeat(CowerBehindADesk.Id, 4),
        StrongBinder.Id,
        PermitA38.Id,
    ];

    // ── Junk ──────────────────────────────────────────────────────────────────────────────────────────────

    // "Unplayable." Nothing else — the whole point is a hand slot that cannot be spent, only removed by
    // something that moves cards without playing them (Archive, discard, exhaust-by-tag).
    public static readonly BnbCard RedTape = new(
        "red_tape", "Red Tape", JunkTag, 0,
        "Unplayable.",
        Seq(),
        Rarity: "junk", Tags: [UnplayableTag]);

    // "Exhaust. No other effect." A dead draw that can at least be thrown away for free.
    public static readonly BnbCard DuplicateCopy = new(
        "duplicate_copy", "Duplicate Copy", JunkTag, 0,
        "Exhaust. No other effect.",
        Seq(),
        Rarity: "junk", Tags: [ExhaustTag]);

    // "Draw 1 card. Exhaust." Cycling, taxed by the Energy it costs.
    public static readonly BnbCard MisfiledPaper = new(
        "misfiled_paper", "Misfiled Paper", JunkTag, 1,
        "Draw 1 card. Exhaust.",
        Draw(1),
        Rarity: "junk", Tags: [ExhaustTag]);

    // "Exhaust. Add a fresh Unsigned Form to your discard pile." It never really leaves: exhausting it in the
    // ordinary way just files the next one, so only Archive — which takes it without playing it — disposes of
    // it for good.
    public static readonly BnbCard UnsignedForm = new(
        "unsigned_form", "Unsigned Form", JunkTag, 0,
        "Exhaust. Add a fresh Unsigned Form to your discard pile.",
        AddCard("unsigned_form", CardZone.DiscardPile),
        Rarity: "junk", Tags: [ExhaustTag, FormTag]);

    public static readonly IReadOnlyList<BnbCard> Junk = [RedTape, DuplicateCopy, MisfiledPaper, UnsignedForm];

    // Starters have upgrades (a campfire can amend one); Junk never does.
    public static IEnumerable<BnbCard> All() =>
    [
        PaperCut, PaperCut.Upgraded("Deal 8 damage.", Damage(8)),
        CowerBehindADesk, CowerBehindADesk.Upgraded("Gain 7 Block.", Block(7)),
        StrongBinder, StrongBinder.Upgraded("Gain 9 Block. Apply 2 Doubt.",
            Seq(Block(9), Apply(Keywords.Doubt, 2))),
        PermitA38, PermitA38.Upgraded("Apply 5 Paperwork.", cost: 1),
        .. Junk,
    ];
}
